image: pandoc/latex:latest  # Official Pandoc image with LaTeX support

stages:
  - build

build_pdf:
  stage: build
  script:
    - pandoc paper.md -o output.pdf --pdf-engine=lualatex  --citeproc --bibliography=paper.bib
  artifacts:
    paths:
      - output.pdf
