image: pandoc/latex:latest  # Uses Pandoc with LaTeX support

stages:
  - build
  - test
  - pages
  - production


build_pdf:
  stage: build
  script:
    # Convert Markdown to PDF with proper citation handling
    - pandoc paper.md -o output.pdf --pdf-engine=lualatex --citeproc --bibliography=paper.bib -V fontsize=12pt -V geometry="margin=1in" -f markdown+lists_without_preceding_blankline
  artifacts:
    paths:
      - output.pdf
  rules:
    - changes:
        - paper.md
        - paper.bib  # Runs the job only if any file in the "paper/" directory changes
        - .gitlab-ci.yml  # Also triggers if the pipeline config changes

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/sphinx/gitlab-ci-sphinx@1.3.0
    inputs:
      project-dir: "."
      image: "ghcr.io/sphinx-doc/sphinx:6.2.1"
  - component: $CI_SERVER_FQDN/to-be-continuous/sphinx/gitlab-ci-sphinx-pages@1.3.0