image: pandoc/latex:latest  # Uses Pandoc with LaTeX support

stages:
  - build

build_pdf:
  stage: build
  script:
    # Generate PDF with proper citation processing and lists
    - pandoc paper.md -o output.pdf --pdf-engine=xelatex --bibliography=paper.bib --citeproc --csl=chicago-author-date.csl
  artifacts:
    paths:
      - pdf/output.pdf
