image: pandoc/latex:latest  # Uses Pandoc with LaTeX support

stages:
  - build

build_pdf:
  stage: build
  script:
    # Convert Markdown to PDF with proper citation handling
    - pandoc paper.md -o output.pdf --pdf-engine=lualatex --citeproc --bibliography=paper.bib -V fontsize=12pt -V geometry="margin=1in" -f markdown+lists_without_preceding_blankline
  artifacts:
    paths:
      - output.pdf
  rules:
    - changes:
        - paper.md
        - paper.bib  # Runs the job only if any file in the "paper/" directory changes
        - .gitlab-ci.yml  # Also triggers if the pipeline config changes
