# image: pandoc/latex:latest  # Uses Pandoc with LaTeX support

stages:
  - build

build-paper:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update && apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-fonts-extra
  script:
    - pandoc paper.md --pdf-engine=xelatex -o paper.pdf
  artifacts:
    paths:
      - paper.pdf
    expire_in: 1 week
  rules:
    - changes:
        - paper.md
        - paper.bib  # Runs the job only if any file in the "paper/" directory changes
        - .gitlab-ci.yml  # Also triggers if the pipeline config changes
